name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    timeout-minutes: 5
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift-version:
          - 6.0.3
          - 6.1.0

    runs-on: ${{ matrix.os }}
    name: Test (${{ matrix.os }}, Swift ${{ matrix.swift-version }})

    steps:
      - uses: actions/checkout@v4

      - name: Setup Swift on Linux
        if: matrix.os == 'ubuntu-latest'
        uses: vapor/swiftly-action@v0.2
        with:
          toolchain: ${{ matrix.swift-version }}
      - name: Setup Swift on macOS
        if: matrix.os == 'macos-latest'
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v
